-- MPA RATINGS
CREATE TABLE IF NOT EXISTS mpa_ratings (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(10) NOT NULL UNIQUE
);

MERGE INTO mpa_ratings (mpa_id, code) KEY (mpa_id) VALUES
    (1, 'G'),
    (2, 'PG'),
    (3, 'PG-13'),
    (4, 'R'),
    (5, 'NC-17');

-- GENRES
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE
    );

MERGE INTO genres (genre_id, name) KEY (genre_id) VALUES
    (1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Мультфильм'),
    (4, 'Триллер'),
    (5, 'Документальный'),
    (6, 'Боевик');

-- USERS
CREATE TABLE IF NOT EXISTS users (
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE NOT NULL
    );

-- FILMS
CREATE TABLE IF NOT EXISTS films (
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL CHECK (duration > 0),

    mpa_id       INTEGER,
    CONSTRAINT fk_films_mpa
    FOREIGN KEY (mpa_id)
    REFERENCES mpa_ratings (mpa_id)
    );

-- FILM_GENRES
CREATE TABLE IF NOT EXISTS film_genres (
    film_id  BIGINT  NOT NULL,
    genre_id INTEGER NOT NULL,

    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film
    FOREIGN KEY (film_id)
    REFERENCES films (film_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_film_genres_genre
    FOREIGN KEY (genre_id)
    REFERENCES genres (genre_id)
    ON DELETE CASCADE
    );

-- FILM LIKES
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_film_likes_film
    FOREIGN KEY (film_id)
    REFERENCES films (film_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_film_likes_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id)
    ON DELETE CASCADE
    );

-- FRIENDSHIPS
CREATE TABLE IF NOT EXISTS friendships (
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status    VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendships_user FOREIGN KEY (user_id)
    REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_friend FOREIGN KEY (friend_id)
    REFERENCES users (user_id) ON DELETE CASCADE
);
